#!/bin/bash

echo "Building Client WASM"
cd server && make client_prod
cd ..

echo "Building Client NPM"
NODE_ENV=production npm run build-prod

echo "Deploying to Git"
cp client.Dockerfile Dockerfile
git add .
git commit -m "Client Deploy"
git push production-client