
#include "weapons/assault-rifle.h"
#include "weapons/pistol.h"
#include "weapons/ammo.h"
#include "weapons/grenade-thrower.h"
#include "weapons/bow.h"
#include "weapons/shotgun.h"
#include "weapons/medkit.h"
#include "weapons/machine-gun.h"
#include "weapons/submachine-gun.h"
#include "weapons/smoke-thrower.h"

#include "objects/lift.h"
#include "objects/spectator-box.h"
#include "objects/supply-bin.h"